<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset=<?= APP_CHARSET ?> >
        <title>KumbiaPHP Framework</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS using skeleton
        –––––––––––––––––––––––––––––––––––––––––––––––––– -->
        <link rel="stylesheet" href="/css/normalize.css">
        <link rel="stylesheet" href="/css/skeleton.css">
        <!-- Custom css -->
        <link rel="stylesheet" href="/css/style.css">
    </head>
    <body>        
        <div class="container">           
            <header class="row">
                <div class="eight columns">
                    <?= Html::img('kumbiaphp.svg', 'KumbiaPHP logo') ?>
                </div>
                <div class="four columns">
                    App: <strong><?= basename(dirname(APP_PATH)) ?></strong> (<?= PRODUCTION ? 'Production' : 'Development' ?>)
                </div>
            </header
            <div class="row">
                <div class="twelve columns">
                    <?php View::content() ?> 
                </div>
            </div>
        </div>
    </body>
</html>
